# ─────────────────────────────────────────────────────────────────────────────
# SonarQube – Configuration Frontend (React / Vite)
# Projet : HRBrain FrontOffice
# ─────────────────────────────────────────────────────────────────────────────
sonar.projectKey=hrbrain-frontend
sonar.projectName=HRBrain FrontOffice
sonar.projectVersion=0.0.1
sonar.host.url=http://172.17.0.2:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/test/**,**/styles/tailwind.css,**/styles/theme.css
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300
