apiVersion: v1
kind: Namespace
metadata:
  name: hrbrain
  labels:
    app.kubernetes.io/part-of: hrbrain
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/part-of: hrbrain-monitoring
