# ─────────────────────────────────────────────────────────────────────────────
# SonarQube – Configuration Backend (NestJS)
# Projet : HRBrain BackOffice
# ─────────────────────────────────────────────────────────────────────────────
sonar.projectKey=hrbrain-backend
sonar.projectName=HRBrain BackOffice
sonar.projectVersion=0.0.1
sonar.host.url=http://sonarqube:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.js,**/coverage/**,**/*.d.ts,**/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
