# ─────────────────────────────────────────────────────────────────────────────
# SonarQube – Configuration Backend (NestJS)
# Projet : HRBrain BackOffice
# ─────────────────────────────────────────────────────────────────────────────
sonar.projectKey=hrbrain-backend
sonar.projectName=HRBrain BackOffice
sonar.projectVersion=0.0.1
sonar.host.url=http://172.17.0.2:9000
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.d.ts,**/test/**
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.sonar.json
sonar.javascript.environments=node
sonar.qualitygate.wait=false
sonar.qualitygate.timeout=300
